### ISSUE TITLE
Input from stdin

### ISSUE THREAD

**Issue by dkasak** [Ayrx/atriage#2]
It seems atriage doesn't support passing input to program-under-test via stdin. This is needed because for some programs this is the only way they'll accept input.

Perhaps when the command passed doesn't contain `@@`, atriage could default to sending the input through stdin?

**Comment by Ayrx** [comment]
Hi!

That's a good point. I personally never ran across that use case because I tend to write my own harnesses. Defaulting to `stdin` if the command doesn't contain `@@` instead of failing hard is a good suggestion though. I'll see if I have time to implement it this week.

In the meantime you could work around this by writing a shell script to take the file input and pipe it to the program under test.

**Comment by dkasak** [comment]
I've taken a stab at implementing this quickly in #3.

And yes, I've used that workaround and it works well for ASAN, but not for exploitable.
